#!/usr/bin/python
import os
import re

devlist = dict()
lastdev = "" 
lastlist = dict()

devicesFile = open("/etc/device_profile", "r")

def SearchDevice():
   try:
     input = raw_input("Please enter full/partial name of a device (or type q to quit):")
     input = input.strip()
     if input is "q":
       exit()  
     for line in devicesFile:
       if line.strip():
         if re.search(input,line.split("~")[1].strip(),re.IGNORECASE):
            devlist[line.split("~")[1]] = line.split("~")[0]
   except:
     exit()
   return devlist

devlist = SearchDevice()

print "============================================================="
print "============= Please choose a device ========================"
print "============================================================="

if len(devlist) <2 and len(devlist) > 0:
   print devlist
   try:
      command = 'ssh ' + devlist.values()[0] 
      if os.system(command) != 0:
         raise Exception
   except Exception:
      command = 'telnet ' + devlist.values()[0] 
      os.system(command)
   exit() 


for dev in devlist:
   print dev + " : " + devlist[dev]

print "============================================================="

try:

  if len(devlist) > 0:
     flag = True
     while flag: 
        a = raw_input("Please enter more specific name of the device in the above list (or type q to quit):")
        b = a.strip()
        print "============================================================="
        if b is "q":
           exit()   
        counter = 0
        for i in devlist:
           c = re.search(b,str(i),re.IGNORECASE)
           if c:
              counter = counter + 1
              print i + ':' + ' ' + devlist[i]
              lastdev = devlist[i]
              lastlist[i] = devlist[i] 
        if counter < 2:
           flag = False
           if lastdev:
              try:
                 command = 'ssh ' + lastdev
                 if os.system(command) != 0:
                    raise Exception
              except Exception:
                 command = 'telnet ' + lastdev
                 os.system(command)
        else:
           devlist = lastlist 
except:
  exit()
  
devicesFile.close()
